setwd("~/Desktop/Coursera/Exploratory Data Analysis")
household_power_consumption <- read.csv("~/Desktop/Coursera/Exploratory Data Analysis/household_power_consumption.txt", header=TRUE, sep=";")
household_power_consumption$NewDate <-as.Date(household_power_consumption$Date, "%d/%m/%Y")
mydata <-subset(household_power_consumption, NewDate =='2007-02-01'| NewDate == '2007-02-02')
x <- paste(mydata$NewDate, mydata$Time)
mydata$Date_time <- strptime(x, "%Y-%m-%d %H:%M:%S")
with(mydata,plot(Date_time, Global_active_power, xlab="", ylab = "Global Active Power (kilowatts)", type = "l"))